name: Deploy DAGs and Plugins to Airflow

on:
  push:
    branches: [main]

jobs:
  deploy-airflow-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy DAGs to Airflow server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user
          key: ${{ secrets.DEPLOY_KEY }}
          source: "dags/*"
          target: "/home/ec2-user/apps/airflow/airflow_home/dags"

      - name: Check if plugins folder exists
        id: check_plugins
        run: |
          if [ -d "plugins" ] && [ "$(ls -A plugins)" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Copy plugins to Airflow server (if exists)
        if: steps.check_plugins.outputs.exists == 'true'
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user
          key: ${{ secrets.DEPLOY_KEY }}
          source: "plugins/*"
          target: "/home/ec2-user/apps/airflow/airflow_home/plugins"

      - name: Restart DAG processor
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            sudo systemctl restart airflow-dag-processor
